import { Category } from "@chec/commerce.js/types/category";
import { CategoryCheckbox } from "@components/category-checkbox";
import { Fragment } from "react";
import type { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { commerceClient } from "@lib/commerce";
import { Button, Form, Input } from "@components/lib";
import { HiSearch, HiUser } from "react-icons/hi";
import { logoWithPineapple, shoppingBag } from "@assets";

type HomeProps = {
  categories: Array<Category>;
};

const Home = ({ categories }: HomeProps): React.ReactElement => (
  <Fragment>
    <Head>
      <title>All Fruver</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Form
      className="shadow-md py-2.5 lg:py-4"
      // eslint-disable-next-line no-console
      onSubmit={(data) => console.log(data)}
    >
      <div className="max-w-2xl px-8 mx-auto">
        <Input
          name="search"
          label="Buscar"
          srLabel
          leadingIcon={HiSearch}
          placeholder="Buscar"
        />
      </div>
      <fieldset className="pl-8 mt-4 min-w-0 flex gap-x-2 overflow-x-auto last:pr-8 sm:last:pr-0 md:justify-center md:pl-0">
        <legend className="sr-only">Categorias</legend>
        {categories.map((category) => (
          <CategoryCheckbox
            key={category.id}
            name={category.name}
            value={category.slug}
            imageURL={
              (category as unknown as { assets: Array<{ url: string }> })
                .assets[0].url
            }
          />
        ))}
      </fieldset>
    </Form>
    <section className="bg-gradient-to-b from-[#E8E8E8] to-gray-100">
      <div className="pl-8 relative py-9 max-w-xl mx-auto overflow-hidden">
        <article className="relative z-10 flex flex-col items-start gap-y-3.5">
          <div className="flex items-center gap-x-1.5">
            <div className="h-14 w-9">
              <Image
                alt="Allfruver initial inside pineapple"
                src={logoWithPineapple as string}
              />
            </div>
            <h1 className="font-bold text-2xl leading-6">
              ¡Tus vegetales <br /> siempre frescos!
            </h1>
          </div>
          <p className="text-sm font-bold leading-4 lg:text-base lg:leading-4">
            Pide lo mejor de tu mercado <br className="lg:hidden" /> local{" "}
            <br className="hidden lg:inline" /> en línea y a domicilio
          </p>
          <Button size="sm" rightIcon={HiUser} appearance="secondary">
            Crea tu cuenta
          </Button>
        </article>
        {/* Background */}
        <Image
          src={shoppingBag}
          alt="Shopping bag"
          className="object-contain object-right-bottom bottom-0 !-right-80 sm:!right-0"
          layout="fill"
          priority
        />
      </div>
    </section>
  </Fragment>
);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const { data: categories } = await commerceClient.categories.list();

  return {
    props: {
      categories,
    },
  };
};

export default Home;
