import { Fragment } from "react";
import Head from "next/head";
import { Layout } from "@components/layout";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>All Fruver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </Fragment>
  );
};

export default Home;
